sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: sean@ctrlplusb.com
  # TODO: run:
  # travis encrypt YOUR_API_KEY --add deploy.api_key
  on:
    branch: master
    tags: true
node_js:
- '7'
script:
- yarn run flow:defs
- yarn run check
after_success:
- yarn run test:coverage:deploy
